import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'AutoDP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen w-full flex-col bg-gradient-to-b from-[#373B44] to-[#4286f4] text-white">
        {children}
      </body>
    </html>
  )
}
